version: '3.7'


services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portn
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/portainer/data/:/data # create directory

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile:ro # create file
      - $PWD/caddy/data:/data # create directory
      - $PWD/caddy/config:/config # create directory

  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - $PWD/nodered_data:/data # create directory

  emqx:
    image: emqx:5.7.2
    container_name: emqx1
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 8883:8883
    volumes:
      - $PWD/emqx/data:/opt/emqx/data
      - $PWD/emqx/certs/cert.pem:/opt/emqx/etc/certs/cert.pem
      - $PWD/emqx/certs/key.pem:/opt/emqx/etc/certs/key.pem
